openapi: 3.0.0

tags:
  - name: Places
  - name: Posts
  - name: News feed
  - name: Media

info:
  title: Travel social network
  description: Социальная сеть с постами путешественников
  version: 1.0.0

paths:
  /places:
    get:
      summary: Поиск мест
      description: Поиск мест с определенными параметрами или общий список всех мест, если параметры не переданы
      tags:
        - Places
      parameters:
        - in: query
          name: name
          description: Название
          required: false
        - in: query
          name: country
          description: Страна
          required: false
        - in: query
          name: category
          description: Категория
          required: false
        - in: query
          name: ratting
          description: Популярность места
          required: false
        - in: query
          name: page
          description: Номер страницы
          required: false
        - in: query
          name: pageSize
          description: Размер страницы
          required: false
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Идентификатор места
                  name:
                    type: string
                    description: Название
                  country:
                    type: string
                    description: Страна
                  category:
                    type: string
                    description: Категория
                required:
                  - id
                  - tiny_url
              examples:
                response:
                  value:
                    - id: "8eff06ed-9acb-44e7-8433-34ecf06a0d90"
                      placeId: "48e2abda-a1e9-4df1-ad1e-5bfe1de39a4f"
                      name: "Байкал"
                      country: "Россия"
                      category: "Водоемы"
                      ratting: "Топ 10 в России"
                      description: "Байкал - одно из величайших озер планеты..."
                      imgUrl: "social.newtwork.ru/img1234534523.img"
        400:
          description: Bad Request
        500:
          description: Server error

  /posts:
    post:
      summary: Опубликовать новый пост
      description: Опубликовать новый пост
      tags:
        - Posts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                placeId:
                  type: string
                  description: Идентификатор места
                text:
                  type: string
                  description: Авторский текст в посте
                imgUrls:
                  type: array
                  description: Ссылки на картинки в посте
                  items:
                    type: string
              required:
                - placeId
                - imgUrls
            examples:
              request:
                value:
                  placeId: "48e2abda-a1e9-4df1-ad1e-5bfe1de39a4f"
                  text: "Байкал… Это место оставляет такие впечатления, что словами трудно передать всю глубину"
                  imgUrls: ["social.newtwork.ru/img1234534523.img", "social.newtwork.ru/img63434423.img"]
      responses:
        200:
          description: Ok
        400:
          description: Bad Request
        500:
          description: Server error

  /posts/likes:
    get:
      summary: Получить лайки
      description: Получить лайки
      tags:
        - Posts
      parameters:
        - in: query
          name: page
          description: Номер страницы
          required: false
        - in: query
          name: pageSize
          description: Размер страницы
          required: false
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                    description: Идентификатор пользователя
                  createdAt:
                    type: string
                    description: Когда поставлен
                required:
                  - userId
                  - createdAt
              examples:
                response:
                  value:
                    - userId: "8eff06ed-9acb-44e7-8433-34ecf06a0d90"
                      createdAt: "2024-11-13 18:21:51.005Z"
        400:
          description: Bad Request
        500:
          description: Server error
    post:
      summary: Поставить лайк
      description: Поставить лайк
      tags:
        - Posts
      parameters:
        - name: id
          in: query
          required: true
          description: Идентификатор поста
      responses:
        200:
          description: Ok
        400:
          description: Bad Request
        500:
          description: Server error

  /posts/comments:
    get:
      summary: Получить комментарий
      description: Получить комментарий
      tags:
        - Posts
      parameters:
        - in: query
          name: page
          description: Номер страницы
          required: false
        - in: query
          name: pageSize
          description: Размер страницы
          required: false
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                    description: Идентификатор пользователя
                  text:
                    type: string
                    description: Комментарий
                  createdAt:
                    type: string
                    description: Когда написан
                required:
                  - userId
                  - text
                  - createdAt
              examples:
                response:
                  value:
                    - userId: "8eff06ed-9acb-44e7-8433-34ecf06a0d90"
                      text: "Как вам водичка?)"
                      createdAt: "2024-11-13 18:21:51.005Z"
        400:
          description: Bad Request
        500:
          description: Server error
    post:
      summary: Оставить комментарий
      description: Оставить комментарий
      tags:
        - Posts
      parameters:
        - name: id
          in: query
          required: true
          description: Идентификатор поста
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: Комментарий
            examples:
              request:
                value:
                  text: "Как вам вода?)"
      responses:
        200:
          description: Ok
        400:
          description: Bad Request
        500:
          description: Server error

  /newsfeed:
    get:
      summary: Подборка свежих популярных постов
      description: Получить самые просматриваемые и обсуждаемые посты
      tags:
        - News feed
      parameters:
        - in: path
          name: placeId
          description: Идентификатор места
          required: false
        - in: query
          name: page
          description: Номер страницы
          required: false
        - in: query
          name: pageSize
          description: Размер страницы
          required: false
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Идентификатор места
                  name:
                    type: string
                    description: Название
                  country:
                    type: string
                    description: Страна
                  category:
                    type: string
                    description: Категория
                required:
                  - id
                  - tiny_url
              examples:
                response:
                  value:
                    - id: "8eff06ed-9acb-44e7-8433-34ecf06a0d90"
                      placeId: "48e2abda-a1e9-4df1-ad1e-5bfe1de39a4f"
                      name: "Байкал"
                      country: "Россия"
                      authorId: "57c39676-274e-4884-9248-48d5e0c3a9ad"
                      text: "Байкал… Это место оставляет такие впечатления, что словами трудно передать всю глубину"
                      imgUrls: [ "social.newtwork.ru/img1234534523.img", "social.newtwork.ru/img63434423.img" ]
                      likes: 535
                      comments:
                        - userId: "811083ed-fd74-4ec0-a339-caad41566a2d"
                          userName: "Natalia"
                          userImg: "social.newtwork.ru/users-img/34234523"
                          text: "Как вам вода?)"
                          createdAt: "2024-11-13 18:21:51.005Z"
                        - userId: "e371eeda-52d4-4f55-9d2f-a8ef882c4c81"
                          userName: "Ilya"
                          userImg: "social.newtwork.ru/users-img/51235703"
                          text: "Тоже был, понравилось"
                          createdAt: "2024-11-14 12:54:31.005Z"
                      createdAt: "2024-11-13 17:45:30.005Z"
        400:
          description: Bad Request
        500:
          description: Server error

  /newsfeed/users/{id}:
    post:
      summary: Подписаться на пользователя
      description: Отслеживать новые посты пользователя и показывать их в своей ленте
      tags:
        - News feed
      parameters:
        - in: path
          name: id
          description: Идентификатор пользователя
          required: false
      responses:
        200:
          description: Ok
        400:
          description: Bad Request
        500:
          description: Server error
    delete:
      summary: Отписаться от пользователя
      description: Перестать отслеживать новые посты пользователя и показывать их в своей ленте
      tags:
        - News feed
      parameters:
        - in: path
          name: id
          description: Идентификатор пользователя
          required: false
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Идентификатор места
                  name:
                    type: string
                    description: Название
                  country:
                    type: string
                    description: Страна
                  category:
                    type: string
                    description: Категория
                required:
                  - id
                  - tiny_url
              examples:
                response:
                  value:
                    - id: "8eff06ed-9acb-44e7-8433-34ecf06a0d90"
                      placeId: "48e2abda-a1e9-4df1-ad1e-5bfe1de39a4f"
                      name: "Байкал"
                      country: "Россия"
                      category: "Водоемы"
                      ratting: "Топ 10 в России"
                      description: "Байкал - одно из величайших озер планеты..."
                      imgUrl: "social.newtwork.ru/img1234534523.img"
        400:
          description: Bad Request
        500:
          description: Server error

  /media/avatars:
    post:
      summary: Обновить аватарку
      description: Обновить аватарку
      tags:
        - Media
      parameters:
        - in: query
          name: file
          description: Фото пользователя
          required: true
      responses:
        200:
          description: Ok
        400:
          description: Bad Request
        500:
          description: Server error

  /media/photos:
    post:
      summary: Загрузить фото
      description: Загрузить фото
      tags:
        - Media
      parameters:
        - in: query
          name: file
          description: Фото с путешествий
          required: true
      responses:
        200:
          description: Ok
        400:
          description: Bad Request
        500:
          description: Server error